services:
  postgres:
    image: postgres:15
    container_name: lms-postgres
    environment:
      POSTGRES_DB: lms-systemDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  lms-app:
    build: .
    container_name: lms-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lms-systemDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_LIQUIBASE_ENABLED: false
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped